(declare-sort ClassTypes 0)
(declare-sort Addr 0)
(declare-sort Msg 0)
(declare-sort inames 0)
(declare-sort ConstVals 0)
(declare-fun type_3 () ClassTypes)
(declare-fun type_0 () ClassTypes)
(declare-fun type_1 () ClassTypes)
(declare-fun type_2 () ClassTypes)
(declare-fun argfun_2 (Msg) Addr)
(declare-fun argfun_1 (Msg) Addr)
(declare-fun argfun_0 (Msg) Addr)
(declare-fun I_CIExit_ActivityfindView () inames)
(declare-fun namefn_ (Msg) inames)
(declare-fun traceFn (Msg) Bool)
(declare-fun I_CIExit_Activityfinish () inames)
(declare-fun I_CBExit_ActivityonPause () inames)
(declare-fun msgLTE (Msg Msg) Bool)
(declare-fun I_CBEnter_ActivityonResume () inames)
(declare-fun constFn (Addr) ConstVals)
(declare-fun const_NULL () ConstVals)
(declare-fun I_CIExit_ViewsetOnClickListener () inames)
(declare-fun I_CBEnter_ActivityonCreate () inames)
(declare-fun addressToTypeFn (Addr) ClassTypes)
(declare-fun dynField_this$0_ (Addr Addr) Bool)
(declare-fun dynField_s_ (Addr Addr) Bool)
(declare-fun const_I1 () ConstVals)
(declare-fun const_I0 () ConstVals)
(declare-fun I_CBEnter_ViewOnClickListeneronClick () inames)
(declare-fun OTHEROTHEROTHER () inames)
(declare-fun INITINIT () inames)
(declare-fun dynField_dynField_s__ (Addr Addr) Bool)
(declare-fun dynField_dynField_this$0__ (Addr Addr) Bool)
(assert (distinct type_2 type_1 type_0 type_3))
(assert true)
(assert (let ((a!1 (exists ((pv-4!3 Addr)
                    (pv-9!7 Addr)
                    (pv-8!6 Addr)
                    (pv-0!0 Addr)
                    (pv-7!8 Addr)
                    (pv-3!2 Addr)
                    (pv-1!1 Addr)
                    (pv-5!9 Addr)
                    (pv-2!4 Addr)
                    (pv-6!5 Addr))
             (let ((a!1 (exists ((msg_j!10 Msg))
                          (and (traceFn msg_j!10)
                               (= (namefn_ msg_j!10) I_CBEnter_ActivityonCreate)
                               (= (argfun_1 msg_j!10) pv-5!9))))
                   (a!2 (exists ((msg_j!11 Msg))
                          (and (traceFn msg_j!11)
                               (= (namefn_ msg_j!11) I_CBEnter_ActivityonCreate)
                               (= (argfun_1 msg_j!11) pv-9!7))))
                   (a!3 (exists ((npv-a!14 Addr))
                          (exists ((npv-v!15 Addr))
                            (let ((a!1 (exists ((msg_j!16 Msg))
                                         (and (traceFn msg_j!16)
                                              (= (namefn_ msg_j!16)
                                                 I_CIExit_ViewsetOnClickListener)
                                              (= (argfun_1 msg_j!16) npv-v!15)
                                              (= (argfun_2 msg_j!16) pv-2!4)
                                              (forall ((msg_j!17 Msg))
                                                (let ((a!1 (and (= (namefn_ msg_j!17)
                                                                   I_CIExit_ViewsetOnClickListener)
                                                                (= (argfun_1 msg_j!17)
                                                                   npv-v!15)
                                                                (= const_NULL
                                                                   (constFn (argfun_2 msg_j!17))))))
                                                (let ((a!2 (=> (and (msgLTE msg_j!16
                                                                            msg_j!17)
                                                                    (not (= msg_j!16
                                                                            msg_j!17)))
                                                               (not a!1))))
                                                  (=> (traceFn msg_j!17) a!2)))))))
                                  (a!3 (or (not (= pv-8!6 npv-v!15))
                                           (not (= const_NULL (constFn pv-7!8)))))
                                  (a!5 (or (not (= pv-3!2 npv-v!15))
                                           (not (= const_NULL (constFn pv-6!5)))))
                                  (a!7 (or (not (= pv-3!2 npv-v!15))
                                           (not (= const_NULL (constFn pv-4!3)))))
                                  (a!8 (exists ((msg_j!18 Msg))
                                         (and (traceFn msg_j!18)
                                              (= (namefn_ msg_j!18)
                                                 I_CIExit_ActivityfindView)
                                              (= (argfun_0 msg_j!18) npv-v!15)
                                              (= (argfun_1 msg_j!18) npv-a!14))))
                                  (a!9 (exists ((msg_j!19 Msg))
                                         (and (traceFn msg_j!19)
                                              (= (namefn_ msg_j!19)
                                                 I_CBEnter_ActivityonResume)
                                              (= (argfun_1 msg_j!19) npv-a!14)
                                              (forall ((msg_j!20 Msg))
                                                (let ((a!1 (not (and (= (namefn_ msg_j!20)
                                                                        I_CBExit_ActivityonPause)
                                                                     (= (argfun_1 msg_j!20)
                                                                        npv-a!14)))))
                                                (let ((a!2 (=> (and (msgLTE msg_j!19
                                                                            msg_j!20)
                                                                    (not (= msg_j!19
                                                                            msg_j!20)))
                                                               a!1)))
                                                  (=> (traceFn msg_j!20) a!2)))))))
                                  (a!10 (exists ((msg_j!21 Msg))
                                          (and (traceFn msg_j!21)
                                               (= (namefn_ msg_j!21)
                                                  I_CIExit_Activityfinish)
                                               (= (argfun_1 msg_j!21) npv-a!14)))))
                            (let ((a!2 (and a!1
                                            (or (not (= npv-v!15 pv-8!6))
                                                (not (= pv-2!4 pv-7!8))))))
                            (let ((a!4 (and (or (and (= npv-v!15 pv-8!6)
                                                     (= pv-2!4 pv-7!8))
                                                a!2)
                                            a!3
                                            (or (not (= npv-v!15 pv-3!2))
                                                (not (= pv-2!4 pv-6!5))))))
                            (let ((a!6 (and (or (and (= npv-v!15 pv-3!2)
                                                     (= pv-2!4 pv-6!5))
                                                a!4)
                                            a!5
                                            (or (not (= npv-v!15 pv-3!2))
                                                (not (= pv-2!4 pv-4!3))))))
                              (and (or (and (= npv-v!15 pv-3!2)
                                            (= pv-2!4 pv-4!3))
                                       a!6)
                                   a!7
                                   (or (and (= npv-v!15 pv-3!2)
                                            (= npv-a!14 pv-5!9))
                                       (and (= npv-v!15 pv-8!6)
                                            (= npv-a!14 pv-9!7))
                                       a!8)
                                   (or a!9 (= npv-a!14 pv-5!9) a!10)))))))))
                   (a!4 (forall ((msg_all Msg))
                          (and (not (= (argfun_0 msg_all) pv-6!5))
                               (not (= (argfun_1 msg_all) pv-6!5))
                               (not (= (argfun_2 msg_all) pv-6!5)))))
                   (a!5 (forall ((msg_all Msg))
                          (and (not (= (argfun_0 msg_all) pv-7!8))
                               (not (= (argfun_1 msg_all) pv-7!8))
                               (not (= (argfun_2 msg_all) pv-7!8))))))
               (and (not (= pv-7!8 pv-1!1))
                    (not (= pv-7!8 pv-0!0))
                    (not (= pv-7!8 pv-2!4))
                    (not (= pv-6!5 pv-1!1))
                    (not (= pv-6!5 pv-0!0))
                    (not (= pv-6!5 pv-2!4))
                    (not (= const_NULL (constFn pv-9!7)))
                    (not (= const_NULL (constFn pv-5!9)))
                    (not (= const_NULL (constFn pv-7!8)))
                    (not (= pv-6!5 pv-2!4))
                    (not (= pv-7!8 pv-2!4))
                    (= const_NULL (constFn pv-0!0))
                    (not (= const_NULL (constFn pv-6!5)))
                    (not (= const_NULL (constFn pv-8!6)))
                    (not (= const_NULL (constFn pv-2!4)))
                    (= const_NULL (constFn pv-4!3))
                    (not (= const_NULL (constFn pv-3!2)))
                    (dynField_s_ pv-1!1 pv-0!0)
                    (dynField_this$0_ pv-2!4 pv-1!1)
                    (or (= (addressToTypeFn pv-0!0) type_2))
                    (or (= (addressToTypeFn pv-1!1) type_1))
                    (or (= (addressToTypeFn pv-3!2) type_0))
                    (or (= (addressToTypeFn pv-2!4) type_3))
                    (or (= (addressToTypeFn pv-6!5) type_3))
                    (or (= (addressToTypeFn pv-8!6) type_0))
                    (or (= (addressToTypeFn pv-9!7) type_1))
                    (or (= (addressToTypeFn pv-7!8) type_3))
                    (or (= (addressToTypeFn pv-5!9) type_1))
                    (not (= pv-9!7 pv-7!8))
                    (not (= pv-8!6 pv-7!8))
                    (not (= pv-8!6 pv-6!5))
                    (not (= pv-7!8 pv-6!5))
                    (not (= pv-9!7 pv-6!5))
                    (not (= pv-3!2 pv-6!5))
                    (not (= pv-5!9 pv-6!5))
                    (not (= pv-5!9 pv-9!7))
                    (not a!1)
                    (not a!2)
                    (forall ((npv-a2!12 Addr))
                      (let ((a!1 (exists ((msg_j!13 Msg))
                                   (and (traceFn msg_j!13)
                                        (= (namefn_ msg_j!13)
                                           I_CIExit_ActivityfindView)
                                        (= (argfun_0 msg_j!13) pv-3!2)
                                        (= (argfun_1 msg_j!13) npv-a2!12)))))
                      (let ((a!2 (and (or (not (= pv-3!2 pv-8!6))
                                          (not (= npv-a2!12 pv-9!7)))
                                      (not a!1))))
                        (or a!2 (= pv-5!9 npv-a2!12)))))
                    a!3
                    (forall ((npv-a2!22 Addr))
                      (let ((a!1 (exists ((msg_j!23 Msg))
                                   (and (traceFn msg_j!23)
                                        (= (namefn_ msg_j!23)
                                           I_CIExit_ActivityfindView)
                                        (= (argfun_0 msg_j!23) pv-8!6)
                                        (= (argfun_1 msg_j!23) npv-a2!22)))))
                        (or (not a!1) (= pv-9!7 npv-a2!22))))
                    a!4
                    a!5)))))
  (not a!1)))
(assert (exists ((pv-6!29 Addr)
         (pv-3!26 Addr)
         (pv-1!25 Addr)
         (pv-0!24 Addr)
         (pv-5!33 Addr)
         (pv-7!32 Addr)
         (pv-4!27 Addr)
         (pv-8!30 Addr)
         (pv-9!31 Addr)
         (pv-2!28 Addr))
  (let ((a!1 (exists ((npv-a!34 Addr))
               (exists ((npv-v!35 Addr))
                 (let ((a!1 (exists ((msg_j!36 Msg))
                              (and (traceFn msg_j!36)
                                   (= (namefn_ msg_j!36)
                                      I_CIExit_ViewsetOnClickListener)
                                   (= (argfun_1 msg_j!36) npv-v!35)
                                   (= (argfun_2 msg_j!36) pv-2!28)
                                   (forall ((msg_j!37 Msg))
                                     (let ((a!1 (and (= (namefn_ msg_j!37)
                                                        I_CIExit_ViewsetOnClickListener)
                                                     (= (argfun_1 msg_j!37)
                                                        npv-v!35)
                                                     (= const_NULL
                                                        (constFn (argfun_2 msg_j!37))))))
                                     (let ((a!2 (=> (and (msgLTE msg_j!36
                                                                 msg_j!37)
                                                         (not (= msg_j!36
                                                                 msg_j!37)))
                                                    (not a!1))))
                                       (=> (traceFn msg_j!37) a!2)))))))
                       (a!3 (or (not (= pv-6!29 npv-v!35))
                                (not (= const_NULL (constFn pv-9!31)))))
                       (a!5 (or (not (= pv-6!29 npv-v!35))
                                (not (= const_NULL (constFn pv-7!32)))))
                       (a!7 (or (not (= pv-4!27 npv-v!35))
                                (not (= const_NULL (constFn pv-3!26)))))
                       (a!8 (exists ((msg_j!38 Msg))
                              (and (traceFn msg_j!38)
                                   (= (namefn_ msg_j!38)
                                      I_CIExit_ActivityfindView)
                                   (= (argfun_0 msg_j!38) npv-v!35)
                                   (= (argfun_1 msg_j!38) npv-a!34))))
                       (a!9 (exists ((msg_j!39 Msg))
                              (and (traceFn msg_j!39)
                                   (= (namefn_ msg_j!39)
                                      I_CBEnter_ActivityonResume)
                                   (= (argfun_1 msg_j!39) npv-a!34)
                                   (forall ((msg_j!40 Msg))
                                     (let ((a!1 (not (and (= (namefn_ msg_j!40)
                                                             I_CBExit_ActivityonPause)
                                                          (= (argfun_1 msg_j!40)
                                                             npv-a!34)))))
                                     (let ((a!2 (=> (and (msgLTE msg_j!39
                                                                 msg_j!40)
                                                         (not (= msg_j!39
                                                                 msg_j!40)))
                                                    a!1)))
                                       (=> (traceFn msg_j!40) a!2)))))))
                       (a!10 (exists ((msg_j!41 Msg))
                               (and (traceFn msg_j!41)
                                    (= (namefn_ msg_j!41)
                                       I_CIExit_Activityfinish)
                                    (= (argfun_1 msg_j!41) npv-a!34)))))
                 (let ((a!2 (and a!1
                                 (or (not (= npv-v!35 pv-6!29))
                                     (not (= pv-2!28 pv-9!31))))))
                 (let ((a!4 (and (or (and (= npv-v!35 pv-6!29)
                                          (= pv-2!28 pv-9!31))
                                     a!2)
                                 a!3
                                 (or (not (= npv-v!35 pv-6!29))
                                     (not (= pv-2!28 pv-7!32))))))
                 (let ((a!6 (and (or (and (= npv-v!35 pv-6!29)
                                          (= pv-2!28 pv-7!32))
                                     a!4)
                                 a!5
                                 (or (not (= npv-v!35 pv-4!27))
                                     (not (= pv-2!28 pv-3!26))))))
                   (and (or (and (= npv-v!35 pv-4!27) (= pv-2!28 pv-3!26)) a!6)
                        a!7
                        (or (and (= npv-v!35 pv-4!27) (= npv-a!34 pv-5!33))
                            (and (= npv-v!35 pv-6!29) (= npv-a!34 pv-8!30))
                            a!8)
                        (or a!9 (= npv-a!34 pv-8!30) a!10)))))))))
        (a!2 (exists ((msg_j!42 Msg))
               (and (traceFn msg_j!42)
                    (= (namefn_ msg_j!42) I_CBEnter_ActivityonCreate)
                    (= (argfun_1 msg_j!42) pv-5!33))))
        (a!3 (exists ((msg_j!43 Msg))
               (and (traceFn msg_j!43)
                    (= (namefn_ msg_j!43) I_CBEnter_ActivityonCreate)
                    (= (argfun_1 msg_j!43) pv-8!30))))
        (a!4 (forall ((msg_all Msg))
               (and (not (= (argfun_0 msg_all) pv-3!26))
                    (not (= (argfun_1 msg_all) pv-3!26))
                    (not (= (argfun_2 msg_all) pv-3!26)))))
        (a!5 (forall ((msg_all Msg))
               (and (not (= (argfun_0 msg_all) pv-9!31))
                    (not (= (argfun_1 msg_all) pv-9!31))
                    (not (= (argfun_2 msg_all) pv-9!31))))))
    (and (not (= pv-9!31 pv-1!25))
         (not (= pv-9!31 pv-0!24))
         (not (= pv-9!31 pv-2!28))
         (not (= pv-3!26 pv-1!25))
         (not (= pv-3!26 pv-0!24))
         (not (= pv-3!26 pv-2!28))
         (not (= const_NULL (constFn pv-9!31)))
         (not (= const_NULL (constFn pv-5!33)))
         (not (= pv-9!31 pv-2!28))
         (= const_NULL (constFn pv-0!24))
         (not (= const_NULL (constFn pv-6!29)))
         (not (= const_NULL (constFn pv-3!26)))
         (= const_NULL (constFn pv-7!32))
         (not (= const_NULL (constFn pv-8!30)))
         (not (= const_NULL (constFn pv-2!28)))
         (not (= pv-3!26 pv-2!28))
         (not (= const_NULL (constFn pv-4!27)))
         (dynField_s_ pv-1!25 pv-0!24)
         (dynField_this$0_ pv-2!28 pv-1!25)
         (or (= (addressToTypeFn pv-0!24) type_2))
         (or (= (addressToTypeFn pv-1!25) type_1))
         (or (= (addressToTypeFn pv-3!26) type_3))
         (or (= (addressToTypeFn pv-4!27) type_0))
         (or (= (addressToTypeFn pv-2!28) type_3))
         (or (= (addressToTypeFn pv-6!29) type_0))
         (or (= (addressToTypeFn pv-8!30) type_1))
         (or (= (addressToTypeFn pv-9!31) type_3))
         (or (= (addressToTypeFn pv-5!33) type_1))
         (not (= pv-8!30 pv-9!31))
         (not (= pv-6!29 pv-9!31))
         (not (= pv-6!29 pv-3!26))
         (not (= pv-7!32 pv-3!26))
         (not (= pv-4!27 pv-3!26))
         (not (= pv-8!30 pv-3!26))
         (not (= pv-9!31 pv-3!26))
         (not (= pv-5!33 pv-3!26))
         a!1
         (not (= pv-5!33 pv-8!30))
         (not a!2)
         (not a!3)
         (forall ((npv-a2!44 Addr))
           (let ((a!1 (exists ((msg_j!45 Msg))
                        (and (traceFn msg_j!45)
                             (= (namefn_ msg_j!45) I_CIExit_ActivityfindView)
                             (= (argfun_0 msg_j!45) pv-6!29)
                             (= (argfun_1 msg_j!45) npv-a2!44)))))
             (or (not a!1) (= pv-8!30 npv-a2!44))))
         (forall ((npv-a2!46 Addr))
           (let ((a!1 (exists ((msg_j!47 Msg))
                        (and (traceFn msg_j!47)
                             (= (namefn_ msg_j!47) I_CIExit_ActivityfindView)
                             (= (argfun_0 msg_j!47) pv-4!27)
                             (= (argfun_1 msg_j!47) npv-a2!46)))))
           (let ((a!2 (and (or (not (= pv-4!27 pv-6!29))
                               (not (= npv-a2!46 pv-8!30)))
                           (not a!1))))
             (or a!2 (= pv-5!33 npv-a2!46)))))
         a!4
         a!5))))
(assert (distinct const_NULL const_I0 const_I1))
(assert (forall ((iname_u!753 inames))
  (or (= iname_u!753 I_CIExit_Activityfinish)
      (= iname_u!753 I_CBExit_ActivityonPause)
      (= iname_u!753 I_CBEnter_ActivityonResume)
      (= iname_u!753 INITINIT)
      (= iname_u!753 OTHEROTHEROTHER)
      (= iname_u!753 I_CIExit_ViewsetOnClickListener)
      (= iname_u!753 I_CBEnter_ViewOnClickListeneronClick)
      (= iname_u!753 I_CBEnter_ActivityonCreate)
      (= iname_u!753 I_CIExit_ActivityfindView))))
(assert (distinct I_CIExit_Activityfinish
          I_CBExit_ActivityonPause
          I_CBEnter_ActivityonResume
          INITINIT
          OTHEROTHEROTHER
          I_CIExit_ViewsetOnClickListener
          I_CBEnter_ViewOnClickListeneronClick
          I_CBEnter_ActivityonCreate
          I_CIExit_ActivityfindView))
(assert (forall ((msg_x!754 Msg)) (msgLTE msg_x!754 msg_x!754)))
(assert (forall ((msg_x!754 Msg) (msg_y!755 Msg) (msg_z!756 Msg))
  (=> (and (msgLTE msg_x!754 msg_y!755) (msgLTE msg_y!755 msg_z!756))
      (msgLTE msg_x!754 msg_z!756))))
(assert (forall ((msg_x!754 Msg) (msg_y!755 Msg))
  (=> (and (msgLTE msg_x!754 msg_y!755) (msgLTE msg_y!755 msg_x!754))
      (= msg_x!754 msg_y!755))))
(assert (forall ((msg_x!754 Msg) (msg_y!755 Msg))
  (or (msgLTE msg_x!754 msg_y!755) (msgLTE msg_y!755 msg_x!754))))
(assert (forall ((a1!757 Addr) (a2!758 Addr) (a3!759 Addr))
  (=> (and (dynField_dynField_s__ a1!757 a2!758)
           (dynField_dynField_s__ a1!757 a3!759))
      (= a2!758 a3!759))))
(assert (forall ((a1!760 Addr) (a2!761 Addr) (a3!762 Addr))
  (=> (and (dynField_dynField_this$0__ a1!760 a2!761)
           (dynField_dynField_this$0__ a1!760 a3!762))
      (= a2!761 a3!762))))

(check-sat)

